package bean;

import java.math.BigDecimal;
import java.util.Date;

public class accession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.quantitative_number
     *
     * @mbggenerated
     */
    private String quantitativeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.plant_heitht
     *
     * @mbggenerated
     */
    private BigDecimal plantHeitht;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.branche_number
     *
     * @mbggenerated
     */
    private BigDecimal brancheNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.stem_node
     *
     * @mbggenerated
     */
    private BigDecimal stemNode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.stem_diameter
     *
     * @mbggenerated
     */
    private BigDecimal stemDiameter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.pod_length
     *
     * @mbggenerated
     */
    private BigDecimal podLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.pod_width
     *
     * @mbggenerated
     */
    private BigDecimal podWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.bottompod_heitht
     *
     * @mbggenerated
     */
    private BigDecimal bottompodHeitht;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.pod500g_number
     *
     * @mbggenerated
     */
    private BigDecimal pod500gNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.growing_duration
     *
     * @mbggenerated
     */
    private BigDecimal growingDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.leaf_length
     *
     * @mbggenerated
     */
    private BigDecimal leafLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.leaf_width
     *
     * @mbggenerated
     */
    private BigDecimal leafWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.stem_heitht
     *
     * @mbggenerated
     */
    private BigDecimal stemHeitht;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.podding_height
     *
     * @mbggenerated
     */
    private BigDecimal poddingHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.oneseedpod_number
     *
     * @mbggenerated
     */
    private BigDecimal oneseedpodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.twoseedpod_number
     *
     * @mbggenerated
     */
    private BigDecimal twoseedpodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.threeseedpod_number
     *
     * @mbggenerated
     */
    private BigDecimal threeseedpodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.fourseedpod_number
     *
     * @mbggenerated
     */
    private BigDecimal fourseedpodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.twoseedpod_length
     *
     * @mbggenerated
     */
    private BigDecimal twoseedpodLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.twoseedpod_width
     *
     * @mbggenerated
     */
    private BigDecimal twoseedpodWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.plantpod_weight
     *
     * @mbggenerated
     */
    private BigDecimal plantpodWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.seed_length
     *
     * @mbggenerated
     */
    private BigDecimal seedLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.seed_width
     *
     * @mbggenerated
     */
    private BigDecimal seedWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.podwall_thickness
     *
     * @mbggenerated
     */
    private BigDecimal podwallThickness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.stem_weight
     *
     * @mbggenerated
     */
    private BigDecimal stemWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.stem_area
     *
     * @mbggenerated
     */
    private BigDecimal stemArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.leaf_lengthwidth
     *
     * @mbggenerated
     */
    private BigDecimal leafLengthwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.ave_nodelength
     *
     * @mbggenerated
     */
    private BigDecimal aveNodelength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.podwall_pod
     *
     * @mbggenerated
     */
    private BigDecimal podwallPod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.seed_pod
     *
     * @mbggenerated
     */
    private BigDecimal seedPod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.seed_lengthwidth
     *
     * @mbggenerated
     */
    private BigDecimal seedLengthwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.stem_density
     *
     * @mbggenerated
     */
    private BigDecimal stemDensity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.podwall_weight
     *
     * @mbggenerated
     */
    private BigDecimal podwallWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.fourseedpod
     *
     * @mbggenerated
     */
    private BigDecimal fourseedpod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.threeseedpod
     *
     * @mbggenerated
     */
    private BigDecimal threeseedpod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.twoseedpod
     *
     * @mbggenerated
     */
    private BigDecimal twoseedpod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.oneseedopd
     *
     * @mbggenerated
     */
    private BigDecimal oneseedopd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.pod_lengthwidth
     *
     * @mbggenerated
     */
    private BigDecimal podLengthwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.singleseedpod_width
     *
     * @mbggenerated
     */
    private BigDecimal singleseedpodWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.singleseedpod_length
     *
     * @mbggenerated
     */
    private BigDecimal singleseedpodLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.plantpod_number
     *
     * @mbggenerated
     */
    private BigDecimal plantpodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.plantseed_number
     *
     * @mbggenerated
     */
    private BigDecimal plantseedNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.plantseed_weight
     *
     * @mbggenerated
     */
    private BigDecimal plantseedWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.podseed_number
     *
     * @mbggenerated
     */
    private BigDecimal podseedNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.freshhundredseed_weight
     *
     * @mbggenerated
     */
    private BigDecimal freshhundredseedWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.hundredseed_weight
     *
     * @mbggenerated
     */
    private BigDecimal hundredseedWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.unitarea_yield
     *
     * @mbggenerated
     */
    private BigDecimal unitareaYield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.protein
     *
     * @mbggenerated
     */
    private BigDecimal protein;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.lysine
     *
     * @mbggenerated
     */
    private BigDecimal lysine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.tryptophan
     *
     * @mbggenerated
     */
    private BigDecimal tryptophan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.phenylalan
     *
     * @mbggenerated
     */
    private BigDecimal phenylalan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.methionine
     *
     * @mbggenerated
     */
    private BigDecimal methionine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.threonine
     *
     * @mbggenerated
     */
    private BigDecimal threonine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.isoleucine
     *
     * @mbggenerated
     */
    private BigDecimal isoleucine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.leucine
     *
     * @mbggenerated
     */
    private BigDecimal leucine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.valine
     *
     * @mbggenerated
     */
    private BigDecimal valine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.cystine
     *
     * @mbggenerated
     */
    private BigDecimal cystine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.protein_11s7s
     *
     * @mbggenerated
     */
    private BigDecimal protein11s7s;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.oil
     *
     * @mbggenerated
     */
    private BigDecimal oil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.stemric
     *
     * @mbggenerated
     */
    private BigDecimal stemric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.palmitic
     *
     * @mbggenerated
     */
    private BigDecimal palmitic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.oleic
     *
     * @mbggenerated
     */
    private BigDecimal oleic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.linoleic
     *
     * @mbggenerated
     */
    private BigDecimal linoleic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.linolenic
     *
     * @mbggenerated
     */
    private BigDecimal linolenic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.sugar
     *
     * @mbggenerated
     */
    private BigDecimal sugar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.isoflavone
     *
     * @mbggenerated
     */
    private BigDecimal isoflavone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accession.last_update
     *
     * @mbggenerated
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.quantitative_number
     *
     * @return the value of accession.quantitative_number
     *
     * @mbggenerated
     */
    public String getQuantitativeNumber() {
        return quantitativeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.quantitative_number
     *
     * @param quantitativeNumber the value for accession.quantitative_number
     *
     * @mbggenerated
     */
    public void setQuantitativeNumber(String quantitativeNumber) {
        this.quantitativeNumber = quantitativeNumber == null ? null : quantitativeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.plant_heitht
     *
     * @return the value of accession.plant_heitht
     *
     * @mbggenerated
     */
    public BigDecimal getPlantHeitht() {
        return plantHeitht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.plant_heitht
     *
     * @param plantHeitht the value for accession.plant_heitht
     *
     * @mbggenerated
     */
    public void setPlantHeitht(BigDecimal plantHeitht) {
        this.plantHeitht = plantHeitht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.branche_number
     *
     * @return the value of accession.branche_number
     *
     * @mbggenerated
     */
    public BigDecimal getBrancheNumber() {
        return brancheNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.branche_number
     *
     * @param brancheNumber the value for accession.branche_number
     *
     * @mbggenerated
     */
    public void setBrancheNumber(BigDecimal brancheNumber) {
        this.brancheNumber = brancheNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.stem_node
     *
     * @return the value of accession.stem_node
     *
     * @mbggenerated
     */
    public BigDecimal getStemNode() {
        return stemNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.stem_node
     *
     * @param stemNode the value for accession.stem_node
     *
     * @mbggenerated
     */
    public void setStemNode(BigDecimal stemNode) {
        this.stemNode = stemNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.stem_diameter
     *
     * @return the value of accession.stem_diameter
     *
     * @mbggenerated
     */
    public BigDecimal getStemDiameter() {
        return stemDiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.stem_diameter
     *
     * @param stemDiameter the value for accession.stem_diameter
     *
     * @mbggenerated
     */
    public void setStemDiameter(BigDecimal stemDiameter) {
        this.stemDiameter = stemDiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.pod_length
     *
     * @return the value of accession.pod_length
     *
     * @mbggenerated
     */
    public BigDecimal getPodLength() {
        return podLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.pod_length
     *
     * @param podLength the value for accession.pod_length
     *
     * @mbggenerated
     */
    public void setPodLength(BigDecimal podLength) {
        this.podLength = podLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.pod_width
     *
     * @return the value of accession.pod_width
     *
     * @mbggenerated
     */
    public BigDecimal getPodWidth() {
        return podWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.pod_width
     *
     * @param podWidth the value for accession.pod_width
     *
     * @mbggenerated
     */
    public void setPodWidth(BigDecimal podWidth) {
        this.podWidth = podWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.bottompod_heitht
     *
     * @return the value of accession.bottompod_heitht
     *
     * @mbggenerated
     */
    public BigDecimal getBottompodHeitht() {
        return bottompodHeitht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.bottompod_heitht
     *
     * @param bottompodHeitht the value for accession.bottompod_heitht
     *
     * @mbggenerated
     */
    public void setBottompodHeitht(BigDecimal bottompodHeitht) {
        this.bottompodHeitht = bottompodHeitht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.pod500g_number
     *
     * @return the value of accession.pod500g_number
     *
     * @mbggenerated
     */
    public BigDecimal getPod500gNumber() {
        return pod500gNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.pod500g_number
     *
     * @param pod500gNumber the value for accession.pod500g_number
     *
     * @mbggenerated
     */
    public void setPod500gNumber(BigDecimal pod500gNumber) {
        this.pod500gNumber = pod500gNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.growing_duration
     *
     * @return the value of accession.growing_duration
     *
     * @mbggenerated
     */
    public BigDecimal getGrowingDuration() {
        return growingDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.growing_duration
     *
     * @param growingDuration the value for accession.growing_duration
     *
     * @mbggenerated
     */
    public void setGrowingDuration(BigDecimal growingDuration) {
        this.growingDuration = growingDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.leaf_length
     *
     * @return the value of accession.leaf_length
     *
     * @mbggenerated
     */
    public BigDecimal getLeafLength() {
        return leafLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.leaf_length
     *
     * @param leafLength the value for accession.leaf_length
     *
     * @mbggenerated
     */
    public void setLeafLength(BigDecimal leafLength) {
        this.leafLength = leafLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.leaf_width
     *
     * @return the value of accession.leaf_width
     *
     * @mbggenerated
     */
    public BigDecimal getLeafWidth() {
        return leafWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.leaf_width
     *
     * @param leafWidth the value for accession.leaf_width
     *
     * @mbggenerated
     */
    public void setLeafWidth(BigDecimal leafWidth) {
        this.leafWidth = leafWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.stem_heitht
     *
     * @return the value of accession.stem_heitht
     *
     * @mbggenerated
     */
    public BigDecimal getStemHeitht() {
        return stemHeitht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.stem_heitht
     *
     * @param stemHeitht the value for accession.stem_heitht
     *
     * @mbggenerated
     */
    public void setStemHeitht(BigDecimal stemHeitht) {
        this.stemHeitht = stemHeitht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.podding_height
     *
     * @return the value of accession.podding_height
     *
     * @mbggenerated
     */
    public BigDecimal getPoddingHeight() {
        return poddingHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.podding_height
     *
     * @param poddingHeight the value for accession.podding_height
     *
     * @mbggenerated
     */
    public void setPoddingHeight(BigDecimal poddingHeight) {
        this.poddingHeight = poddingHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.oneseedpod_number
     *
     * @return the value of accession.oneseedpod_number
     *
     * @mbggenerated
     */
    public BigDecimal getOneseedpodNumber() {
        return oneseedpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.oneseedpod_number
     *
     * @param oneseedpodNumber the value for accession.oneseedpod_number
     *
     * @mbggenerated
     */
    public void setOneseedpodNumber(BigDecimal oneseedpodNumber) {
        this.oneseedpodNumber = oneseedpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.twoseedpod_number
     *
     * @return the value of accession.twoseedpod_number
     *
     * @mbggenerated
     */
    public BigDecimal getTwoseedpodNumber() {
        return twoseedpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.twoseedpod_number
     *
     * @param twoseedpodNumber the value for accession.twoseedpod_number
     *
     * @mbggenerated
     */
    public void setTwoseedpodNumber(BigDecimal twoseedpodNumber) {
        this.twoseedpodNumber = twoseedpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.threeseedpod_number
     *
     * @return the value of accession.threeseedpod_number
     *
     * @mbggenerated
     */
    public BigDecimal getThreeseedpodNumber() {
        return threeseedpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.threeseedpod_number
     *
     * @param threeseedpodNumber the value for accession.threeseedpod_number
     *
     * @mbggenerated
     */
    public void setThreeseedpodNumber(BigDecimal threeseedpodNumber) {
        this.threeseedpodNumber = threeseedpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.fourseedpod_number
     *
     * @return the value of accession.fourseedpod_number
     *
     * @mbggenerated
     */
    public BigDecimal getFourseedpodNumber() {
        return fourseedpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.fourseedpod_number
     *
     * @param fourseedpodNumber the value for accession.fourseedpod_number
     *
     * @mbggenerated
     */
    public void setFourseedpodNumber(BigDecimal fourseedpodNumber) {
        this.fourseedpodNumber = fourseedpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.twoseedpod_length
     *
     * @return the value of accession.twoseedpod_length
     *
     * @mbggenerated
     */
    public BigDecimal getTwoseedpodLength() {
        return twoseedpodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.twoseedpod_length
     *
     * @param twoseedpodLength the value for accession.twoseedpod_length
     *
     * @mbggenerated
     */
    public void setTwoseedpodLength(BigDecimal twoseedpodLength) {
        this.twoseedpodLength = twoseedpodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.twoseedpod_width
     *
     * @return the value of accession.twoseedpod_width
     *
     * @mbggenerated
     */
    public BigDecimal getTwoseedpodWidth() {
        return twoseedpodWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.twoseedpod_width
     *
     * @param twoseedpodWidth the value for accession.twoseedpod_width
     *
     * @mbggenerated
     */
    public void setTwoseedpodWidth(BigDecimal twoseedpodWidth) {
        this.twoseedpodWidth = twoseedpodWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.plantpod_weight
     *
     * @return the value of accession.plantpod_weight
     *
     * @mbggenerated
     */
    public BigDecimal getPlantpodWeight() {
        return plantpodWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.plantpod_weight
     *
     * @param plantpodWeight the value for accession.plantpod_weight
     *
     * @mbggenerated
     */
    public void setPlantpodWeight(BigDecimal plantpodWeight) {
        this.plantpodWeight = plantpodWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.seed_length
     *
     * @return the value of accession.seed_length
     *
     * @mbggenerated
     */
    public BigDecimal getSeedLength() {
        return seedLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.seed_length
     *
     * @param seedLength the value for accession.seed_length
     *
     * @mbggenerated
     */
    public void setSeedLength(BigDecimal seedLength) {
        this.seedLength = seedLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.seed_width
     *
     * @return the value of accession.seed_width
     *
     * @mbggenerated
     */
    public BigDecimal getSeedWidth() {
        return seedWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.seed_width
     *
     * @param seedWidth the value for accession.seed_width
     *
     * @mbggenerated
     */
    public void setSeedWidth(BigDecimal seedWidth) {
        this.seedWidth = seedWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.podwall_thickness
     *
     * @return the value of accession.podwall_thickness
     *
     * @mbggenerated
     */
    public BigDecimal getPodwallThickness() {
        return podwallThickness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.podwall_thickness
     *
     * @param podwallThickness the value for accession.podwall_thickness
     *
     * @mbggenerated
     */
    public void setPodwallThickness(BigDecimal podwallThickness) {
        this.podwallThickness = podwallThickness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.stem_weight
     *
     * @return the value of accession.stem_weight
     *
     * @mbggenerated
     */
    public BigDecimal getStemWeight() {
        return stemWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.stem_weight
     *
     * @param stemWeight the value for accession.stem_weight
     *
     * @mbggenerated
     */
    public void setStemWeight(BigDecimal stemWeight) {
        this.stemWeight = stemWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.stem_area
     *
     * @return the value of accession.stem_area
     *
     * @mbggenerated
     */
    public BigDecimal getStemArea() {
        return stemArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.stem_area
     *
     * @param stemArea the value for accession.stem_area
     *
     * @mbggenerated
     */
    public void setStemArea(BigDecimal stemArea) {
        this.stemArea = stemArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.leaf_lengthwidth
     *
     * @return the value of accession.leaf_lengthwidth
     *
     * @mbggenerated
     */
    public BigDecimal getLeafLengthwidth() {
        return leafLengthwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.leaf_lengthwidth
     *
     * @param leafLengthwidth the value for accession.leaf_lengthwidth
     *
     * @mbggenerated
     */
    public void setLeafLengthwidth(BigDecimal leafLengthwidth) {
        this.leafLengthwidth = leafLengthwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.ave_nodelength
     *
     * @return the value of accession.ave_nodelength
     *
     * @mbggenerated
     */
    public BigDecimal getAveNodelength() {
        return aveNodelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.ave_nodelength
     *
     * @param aveNodelength the value for accession.ave_nodelength
     *
     * @mbggenerated
     */
    public void setAveNodelength(BigDecimal aveNodelength) {
        this.aveNodelength = aveNodelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.podwall_pod
     *
     * @return the value of accession.podwall_pod
     *
     * @mbggenerated
     */
    public BigDecimal getPodwallPod() {
        return podwallPod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.podwall_pod
     *
     * @param podwallPod the value for accession.podwall_pod
     *
     * @mbggenerated
     */
    public void setPodwallPod(BigDecimal podwallPod) {
        this.podwallPod = podwallPod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.seed_pod
     *
     * @return the value of accession.seed_pod
     *
     * @mbggenerated
     */
    public BigDecimal getSeedPod() {
        return seedPod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.seed_pod
     *
     * @param seedPod the value for accession.seed_pod
     *
     * @mbggenerated
     */
    public void setSeedPod(BigDecimal seedPod) {
        this.seedPod = seedPod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.seed_lengthwidth
     *
     * @return the value of accession.seed_lengthwidth
     *
     * @mbggenerated
     */
    public BigDecimal getSeedLengthwidth() {
        return seedLengthwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.seed_lengthwidth
     *
     * @param seedLengthwidth the value for accession.seed_lengthwidth
     *
     * @mbggenerated
     */
    public void setSeedLengthwidth(BigDecimal seedLengthwidth) {
        this.seedLengthwidth = seedLengthwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.stem_density
     *
     * @return the value of accession.stem_density
     *
     * @mbggenerated
     */
    public BigDecimal getStemDensity() {
        return stemDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.stem_density
     *
     * @param stemDensity the value for accession.stem_density
     *
     * @mbggenerated
     */
    public void setStemDensity(BigDecimal stemDensity) {
        this.stemDensity = stemDensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.podwall_weight
     *
     * @return the value of accession.podwall_weight
     *
     * @mbggenerated
     */
    public BigDecimal getPodwallWeight() {
        return podwallWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.podwall_weight
     *
     * @param podwallWeight the value for accession.podwall_weight
     *
     * @mbggenerated
     */
    public void setPodwallWeight(BigDecimal podwallWeight) {
        this.podwallWeight = podwallWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.fourseedpod
     *
     * @return the value of accession.fourseedpod
     *
     * @mbggenerated
     */
    public BigDecimal getFourseedpod() {
        return fourseedpod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.fourseedpod
     *
     * @param fourseedpod the value for accession.fourseedpod
     *
     * @mbggenerated
     */
    public void setFourseedpod(BigDecimal fourseedpod) {
        this.fourseedpod = fourseedpod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.threeseedpod
     *
     * @return the value of accession.threeseedpod
     *
     * @mbggenerated
     */
    public BigDecimal getThreeseedpod() {
        return threeseedpod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.threeseedpod
     *
     * @param threeseedpod the value for accession.threeseedpod
     *
     * @mbggenerated
     */
    public void setThreeseedpod(BigDecimal threeseedpod) {
        this.threeseedpod = threeseedpod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.twoseedpod
     *
     * @return the value of accession.twoseedpod
     *
     * @mbggenerated
     */
    public BigDecimal getTwoseedpod() {
        return twoseedpod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.twoseedpod
     *
     * @param twoseedpod the value for accession.twoseedpod
     *
     * @mbggenerated
     */
    public void setTwoseedpod(BigDecimal twoseedpod) {
        this.twoseedpod = twoseedpod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.oneseedopd
     *
     * @return the value of accession.oneseedopd
     *
     * @mbggenerated
     */
    public BigDecimal getOneseedopd() {
        return oneseedopd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.oneseedopd
     *
     * @param oneseedopd the value for accession.oneseedopd
     *
     * @mbggenerated
     */
    public void setOneseedopd(BigDecimal oneseedopd) {
        this.oneseedopd = oneseedopd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.pod_lengthwidth
     *
     * @return the value of accession.pod_lengthwidth
     *
     * @mbggenerated
     */
    public BigDecimal getPodLengthwidth() {
        return podLengthwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.pod_lengthwidth
     *
     * @param podLengthwidth the value for accession.pod_lengthwidth
     *
     * @mbggenerated
     */
    public void setPodLengthwidth(BigDecimal podLengthwidth) {
        this.podLengthwidth = podLengthwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.singleseedpod_width
     *
     * @return the value of accession.singleseedpod_width
     *
     * @mbggenerated
     */
    public BigDecimal getSingleseedpodWidth() {
        return singleseedpodWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.singleseedpod_width
     *
     * @param singleseedpodWidth the value for accession.singleseedpod_width
     *
     * @mbggenerated
     */
    public void setSingleseedpodWidth(BigDecimal singleseedpodWidth) {
        this.singleseedpodWidth = singleseedpodWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.singleseedpod_length
     *
     * @return the value of accession.singleseedpod_length
     *
     * @mbggenerated
     */
    public BigDecimal getSingleseedpodLength() {
        return singleseedpodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.singleseedpod_length
     *
     * @param singleseedpodLength the value for accession.singleseedpod_length
     *
     * @mbggenerated
     */
    public void setSingleseedpodLength(BigDecimal singleseedpodLength) {
        this.singleseedpodLength = singleseedpodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.plantpod_number
     *
     * @return the value of accession.plantpod_number
     *
     * @mbggenerated
     */
    public BigDecimal getPlantpodNumber() {
        return plantpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.plantpod_number
     *
     * @param plantpodNumber the value for accession.plantpod_number
     *
     * @mbggenerated
     */
    public void setPlantpodNumber(BigDecimal plantpodNumber) {
        this.plantpodNumber = plantpodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.plantseed_number
     *
     * @return the value of accession.plantseed_number
     *
     * @mbggenerated
     */
    public BigDecimal getPlantseedNumber() {
        return plantseedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.plantseed_number
     *
     * @param plantseedNumber the value for accession.plantseed_number
     *
     * @mbggenerated
     */
    public void setPlantseedNumber(BigDecimal plantseedNumber) {
        this.plantseedNumber = plantseedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.plantseed_weight
     *
     * @return the value of accession.plantseed_weight
     *
     * @mbggenerated
     */
    public BigDecimal getPlantseedWeight() {
        return plantseedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.plantseed_weight
     *
     * @param plantseedWeight the value for accession.plantseed_weight
     *
     * @mbggenerated
     */
    public void setPlantseedWeight(BigDecimal plantseedWeight) {
        this.plantseedWeight = plantseedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.podseed_number
     *
     * @return the value of accession.podseed_number
     *
     * @mbggenerated
     */
    public BigDecimal getPodseedNumber() {
        return podseedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.podseed_number
     *
     * @param podseedNumber the value for accession.podseed_number
     *
     * @mbggenerated
     */
    public void setPodseedNumber(BigDecimal podseedNumber) {
        this.podseedNumber = podseedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.freshhundredseed_weight
     *
     * @return the value of accession.freshhundredseed_weight
     *
     * @mbggenerated
     */
    public BigDecimal getFreshhundredseedWeight() {
        return freshhundredseedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.freshhundredseed_weight
     *
     * @param freshhundredseedWeight the value for accession.freshhundredseed_weight
     *
     * @mbggenerated
     */
    public void setFreshhundredseedWeight(BigDecimal freshhundredseedWeight) {
        this.freshhundredseedWeight = freshhundredseedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.hundredseed_weight
     *
     * @return the value of accession.hundredseed_weight
     *
     * @mbggenerated
     */
    public BigDecimal getHundredseedWeight() {
        return hundredseedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.hundredseed_weight
     *
     * @param hundredseedWeight the value for accession.hundredseed_weight
     *
     * @mbggenerated
     */
    public void setHundredseedWeight(BigDecimal hundredseedWeight) {
        this.hundredseedWeight = hundredseedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.unitarea_yield
     *
     * @return the value of accession.unitarea_yield
     *
     * @mbggenerated
     */
    public BigDecimal getUnitareaYield() {
        return unitareaYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.unitarea_yield
     *
     * @param unitareaYield the value for accession.unitarea_yield
     *
     * @mbggenerated
     */
    public void setUnitareaYield(BigDecimal unitareaYield) {
        this.unitareaYield = unitareaYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.protein
     *
     * @return the value of accession.protein
     *
     * @mbggenerated
     */
    public BigDecimal getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.protein
     *
     * @param protein the value for accession.protein
     *
     * @mbggenerated
     */
    public void setProtein(BigDecimal protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.lysine
     *
     * @return the value of accession.lysine
     *
     * @mbggenerated
     */
    public BigDecimal getLysine() {
        return lysine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.lysine
     *
     * @param lysine the value for accession.lysine
     *
     * @mbggenerated
     */
    public void setLysine(BigDecimal lysine) {
        this.lysine = lysine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.tryptophan
     *
     * @return the value of accession.tryptophan
     *
     * @mbggenerated
     */
    public BigDecimal getTryptophan() {
        return tryptophan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.tryptophan
     *
     * @param tryptophan the value for accession.tryptophan
     *
     * @mbggenerated
     */
    public void setTryptophan(BigDecimal tryptophan) {
        this.tryptophan = tryptophan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.phenylalan
     *
     * @return the value of accession.phenylalan
     *
     * @mbggenerated
     */
    public BigDecimal getPhenylalan() {
        return phenylalan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.phenylalan
     *
     * @param phenylalan the value for accession.phenylalan
     *
     * @mbggenerated
     */
    public void setPhenylalan(BigDecimal phenylalan) {
        this.phenylalan = phenylalan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.methionine
     *
     * @return the value of accession.methionine
     *
     * @mbggenerated
     */
    public BigDecimal getMethionine() {
        return methionine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.methionine
     *
     * @param methionine the value for accession.methionine
     *
     * @mbggenerated
     */
    public void setMethionine(BigDecimal methionine) {
        this.methionine = methionine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.threonine
     *
     * @return the value of accession.threonine
     *
     * @mbggenerated
     */
    public BigDecimal getThreonine() {
        return threonine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.threonine
     *
     * @param threonine the value for accession.threonine
     *
     * @mbggenerated
     */
    public void setThreonine(BigDecimal threonine) {
        this.threonine = threonine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.isoleucine
     *
     * @return the value of accession.isoleucine
     *
     * @mbggenerated
     */
    public BigDecimal getIsoleucine() {
        return isoleucine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.isoleucine
     *
     * @param isoleucine the value for accession.isoleucine
     *
     * @mbggenerated
     */
    public void setIsoleucine(BigDecimal isoleucine) {
        this.isoleucine = isoleucine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.leucine
     *
     * @return the value of accession.leucine
     *
     * @mbggenerated
     */
    public BigDecimal getLeucine() {
        return leucine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.leucine
     *
     * @param leucine the value for accession.leucine
     *
     * @mbggenerated
     */
    public void setLeucine(BigDecimal leucine) {
        this.leucine = leucine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.valine
     *
     * @return the value of accession.valine
     *
     * @mbggenerated
     */
    public BigDecimal getValine() {
        return valine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.valine
     *
     * @param valine the value for accession.valine
     *
     * @mbggenerated
     */
    public void setValine(BigDecimal valine) {
        this.valine = valine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.cystine
     *
     * @return the value of accession.cystine
     *
     * @mbggenerated
     */
    public BigDecimal getCystine() {
        return cystine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.cystine
     *
     * @param cystine the value for accession.cystine
     *
     * @mbggenerated
     */
    public void setCystine(BigDecimal cystine) {
        this.cystine = cystine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.protein_11s7s
     *
     * @return the value of accession.protein_11s7s
     *
     * @mbggenerated
     */
    public BigDecimal getProtein11s7s() {
        return protein11s7s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.protein_11s7s
     *
     * @param protein11s7s the value for accession.protein_11s7s
     *
     * @mbggenerated
     */
    public void setProtein11s7s(BigDecimal protein11s7s) {
        this.protein11s7s = protein11s7s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.oil
     *
     * @return the value of accession.oil
     *
     * @mbggenerated
     */
    public BigDecimal getOil() {
        return oil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.oil
     *
     * @param oil the value for accession.oil
     *
     * @mbggenerated
     */
    public void setOil(BigDecimal oil) {
        this.oil = oil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.stemric
     *
     * @return the value of accession.stemric
     *
     * @mbggenerated
     */
    public BigDecimal getStemric() {
        return stemric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.stemric
     *
     * @param stemric the value for accession.stemric
     *
     * @mbggenerated
     */
    public void setStemric(BigDecimal stemric) {
        this.stemric = stemric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.palmitic
     *
     * @return the value of accession.palmitic
     *
     * @mbggenerated
     */
    public BigDecimal getPalmitic() {
        return palmitic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.palmitic
     *
     * @param palmitic the value for accession.palmitic
     *
     * @mbggenerated
     */
    public void setPalmitic(BigDecimal palmitic) {
        this.palmitic = palmitic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.oleic
     *
     * @return the value of accession.oleic
     *
     * @mbggenerated
     */
    public BigDecimal getOleic() {
        return oleic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.oleic
     *
     * @param oleic the value for accession.oleic
     *
     * @mbggenerated
     */
    public void setOleic(BigDecimal oleic) {
        this.oleic = oleic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.linoleic
     *
     * @return the value of accession.linoleic
     *
     * @mbggenerated
     */
    public BigDecimal getLinoleic() {
        return linoleic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.linoleic
     *
     * @param linoleic the value for accession.linoleic
     *
     * @mbggenerated
     */
    public void setLinoleic(BigDecimal linoleic) {
        this.linoleic = linoleic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.linolenic
     *
     * @return the value of accession.linolenic
     *
     * @mbggenerated
     */
    public BigDecimal getLinolenic() {
        return linolenic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.linolenic
     *
     * @param linolenic the value for accession.linolenic
     *
     * @mbggenerated
     */
    public void setLinolenic(BigDecimal linolenic) {
        this.linolenic = linolenic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.sugar
     *
     * @return the value of accession.sugar
     *
     * @mbggenerated
     */
    public BigDecimal getSugar() {
        return sugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.sugar
     *
     * @param sugar the value for accession.sugar
     *
     * @mbggenerated
     */
    public void setSugar(BigDecimal sugar) {
        this.sugar = sugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.isoflavone
     *
     * @return the value of accession.isoflavone
     *
     * @mbggenerated
     */
    public BigDecimal getIsoflavone() {
        return isoflavone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.isoflavone
     *
     * @param isoflavone the value for accession.isoflavone
     *
     * @mbggenerated
     */
    public void setIsoflavone(BigDecimal isoflavone) {
        this.isoflavone = isoflavone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accession.last_update
     *
     * @return the value of accession.last_update
     *
     * @mbggenerated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accession.last_update
     *
     * @param lastUpdate the value for accession.last_update
     *
     * @mbggenerated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}