package bean;

import java.util.Date;

public class accessionimage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessionimage.accessionimage_number
     *
     * @mbggenerated
     */
    private Integer accessionimageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessionimage.accessionimage_name
     *
     * @mbggenerated
     */
    private String accessionimageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessionimage.accessionbase_number
     *
     * @mbggenerated
     */
    private String accessionbaseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessionimage.accessionimage_path
     *
     * @mbggenerated
     */
    private String accessionimagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessionimage.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessionimage.last_update
     *
     * @mbggenerated
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessionimage.accessionimage_number
     *
     * @return the value of accessionimage.accessionimage_number
     *
     * @mbggenerated
     */
    public Integer getAccessionimageNumber() {
        return accessionimageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessionimage.accessionimage_number
     *
     * @param accessionimageNumber the value for accessionimage.accessionimage_number
     *
     * @mbggenerated
     */
    public void setAccessionimageNumber(Integer accessionimageNumber) {
        this.accessionimageNumber = accessionimageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessionimage.accessionimage_name
     *
     * @return the value of accessionimage.accessionimage_name
     *
     * @mbggenerated
     */
    public String getAccessionimageName() {
        return accessionimageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessionimage.accessionimage_name
     *
     * @param accessionimageName the value for accessionimage.accessionimage_name
     *
     * @mbggenerated
     */
    public void setAccessionimageName(String accessionimageName) {
        this.accessionimageName = accessionimageName == null ? null : accessionimageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessionimage.accessionbase_number
     *
     * @return the value of accessionimage.accessionbase_number
     *
     * @mbggenerated
     */
    public String getAccessionbaseNumber() {
        return accessionbaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessionimage.accessionbase_number
     *
     * @param accessionbaseNumber the value for accessionimage.accessionbase_number
     *
     * @mbggenerated
     */
    public void setAccessionbaseNumber(String accessionbaseNumber) {
        this.accessionbaseNumber = accessionbaseNumber == null ? null : accessionbaseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessionimage.accessionimage_path
     *
     * @return the value of accessionimage.accessionimage_path
     *
     * @mbggenerated
     */
    public String getAccessionimagePath() {
        return accessionimagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessionimage.accessionimage_path
     *
     * @param accessionimagePath the value for accessionimage.accessionimage_path
     *
     * @mbggenerated
     */
    public void setAccessionimagePath(String accessionimagePath) {
        this.accessionimagePath = accessionimagePath == null ? null : accessionimagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessionimage.remark
     *
     * @return the value of accessionimage.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessionimage.remark
     *
     * @param remark the value for accessionimage.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessionimage.last_update
     *
     * @return the value of accessionimage.last_update
     *
     * @mbggenerated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessionimage.last_update
     *
     * @param lastUpdate the value for accessionimage.last_update
     *
     * @mbggenerated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}