package bean;

public class breedingmothod {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breedingmothod.breedingmothod_number
     *
     * @mbggenerated
     */
    private Integer breedingmothodNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breedingmothod.breedingmothod_chname
     *
     * @mbggenerated
     */
    private String breedingmothodChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breedingmothod.breedingmothod_enname
     *
     * @mbggenerated
     */
    private String breedingmothodEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breedingmothod.breedingmothod_number
     *
     * @return the value of breedingmothod.breedingmothod_number
     *
     * @mbggenerated
     */
    public Integer getBreedingmothodNumber() {
        return breedingmothodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breedingmothod.breedingmothod_number
     *
     * @param breedingmothodNumber the value for breedingmothod.breedingmothod_number
     *
     * @mbggenerated
     */
    public void setBreedingmothodNumber(Integer breedingmothodNumber) {
        this.breedingmothodNumber = breedingmothodNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breedingmothod.breedingmothod_chname
     *
     * @return the value of breedingmothod.breedingmothod_chname
     *
     * @mbggenerated
     */
    public String getBreedingmothodChname() {
        return breedingmothodChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breedingmothod.breedingmothod_chname
     *
     * @param breedingmothodChname the value for breedingmothod.breedingmothod_chname
     *
     * @mbggenerated
     */
    public void setBreedingmothodChname(String breedingmothodChname) {
        this.breedingmothodChname = breedingmothodChname == null ? null : breedingmothodChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breedingmothod.breedingmothod_enname
     *
     * @return the value of breedingmothod.breedingmothod_enname
     *
     * @mbggenerated
     */
    public String getBreedingmothodEnname() {
        return breedingmothodEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breedingmothod.breedingmothod_enname
     *
     * @param breedingmothodEnname the value for breedingmothod.breedingmothod_enname
     *
     * @mbggenerated
     */
    public void setBreedingmothodEnname(String breedingmothodEnname) {
        this.breedingmothodEnname = breedingmothodEnname == null ? null : breedingmothodEnname.trim();
    }
}