package bean;

public class corecollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corecollection.corecollection_id
     *
     * @mbggenerated
     */
    private Integer corecollectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corecollection.corecollection_number
     *
     * @mbggenerated
     */
    private Integer corecollectionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corecollection.corecollection_chname
     *
     * @mbggenerated
     */
    private String corecollectionChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corecollection.corecollection_enname
     *
     * @mbggenerated
     */
    private String corecollectionEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corecollection.corecollection_id
     *
     * @return the value of corecollection.corecollection_id
     *
     * @mbggenerated
     */
    public Integer getCorecollectionId() {
        return corecollectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corecollection.corecollection_id
     *
     * @param corecollectionId the value for corecollection.corecollection_id
     *
     * @mbggenerated
     */
    public void setCorecollectionId(Integer corecollectionId) {
        this.corecollectionId = corecollectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corecollection.corecollection_number
     *
     * @return the value of corecollection.corecollection_number
     *
     * @mbggenerated
     */
    public Integer getCorecollectionNumber() {
        return corecollectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corecollection.corecollection_number
     *
     * @param corecollectionNumber the value for corecollection.corecollection_number
     *
     * @mbggenerated
     */
    public void setCorecollectionNumber(Integer corecollectionNumber) {
        this.corecollectionNumber = corecollectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corecollection.corecollection_chname
     *
     * @return the value of corecollection.corecollection_chname
     *
     * @mbggenerated
     */
    public String getCorecollectionChname() {
        return corecollectionChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corecollection.corecollection_chname
     *
     * @param corecollectionChname the value for corecollection.corecollection_chname
     *
     * @mbggenerated
     */
    public void setCorecollectionChname(String corecollectionChname) {
        this.corecollectionChname = corecollectionChname == null ? null : corecollectionChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corecollection.corecollection_enname
     *
     * @return the value of corecollection.corecollection_enname
     *
     * @mbggenerated
     */
    public String getCorecollectionEnname() {
        return corecollectionEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corecollection.corecollection_enname
     *
     * @param corecollectionEnname the value for corecollection.corecollection_enname
     *
     * @mbggenerated
     */
    public void setCorecollectionEnname(String corecollectionEnname) {
        this.corecollectionEnname = corecollectionEnname == null ? null : corecollectionEnname.trim();
    }
}