package bean;

import java.util.Date;

public class fingerprint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.fingerprint_number
     *
     * @mbggenerated
     */
    private Integer fingerprintNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.accessionbase_number
     *
     * @mbggenerated
     */
    private String accessionbaseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.fingerprint_num
     *
     * @mbggenerated
     */
    private String fingerprintNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.primer_path
     *
     * @mbggenerated
     */
    private String primerPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.marker_path
     *
     * @mbggenerated
     */
    private String markerPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.id_path
     *
     * @mbggenerated
     */
    private String idPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.last_update
     *
     * @mbggenerated
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.fingerprint_number
     *
     * @return the value of fingerprint.fingerprint_number
     *
     * @mbggenerated
     */
    public Integer getFingerprintNumber() {
        return fingerprintNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.fingerprint_number
     *
     * @param fingerprintNumber the value for fingerprint.fingerprint_number
     *
     * @mbggenerated
     */
    public void setFingerprintNumber(Integer fingerprintNumber) {
        this.fingerprintNumber = fingerprintNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.accessionbase_number
     *
     * @return the value of fingerprint.accessionbase_number
     *
     * @mbggenerated
     */
    public String getAccessionbaseNumber() {
        return accessionbaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.accessionbase_number
     *
     * @param accessionbaseNumber the value for fingerprint.accessionbase_number
     *
     * @mbggenerated
     */
    public void setAccessionbaseNumber(String accessionbaseNumber) {
        this.accessionbaseNumber = accessionbaseNumber == null ? null : accessionbaseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.fingerprint_num
     *
     * @return the value of fingerprint.fingerprint_num
     *
     * @mbggenerated
     */
    public String getFingerprintNum() {
        return fingerprintNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.fingerprint_num
     *
     * @param fingerprintNum the value for fingerprint.fingerprint_num
     *
     * @mbggenerated
     */
    public void setFingerprintNum(String fingerprintNum) {
        this.fingerprintNum = fingerprintNum == null ? null : fingerprintNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.primer_path
     *
     * @return the value of fingerprint.primer_path
     *
     * @mbggenerated
     */
    public String getPrimerPath() {
        return primerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.primer_path
     *
     * @param primerPath the value for fingerprint.primer_path
     *
     * @mbggenerated
     */
    public void setPrimerPath(String primerPath) {
        this.primerPath = primerPath == null ? null : primerPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.marker_path
     *
     * @return the value of fingerprint.marker_path
     *
     * @mbggenerated
     */
    public String getMarkerPath() {
        return markerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.marker_path
     *
     * @param markerPath the value for fingerprint.marker_path
     *
     * @mbggenerated
     */
    public void setMarkerPath(String markerPath) {
        this.markerPath = markerPath == null ? null : markerPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.id_path
     *
     * @return the value of fingerprint.id_path
     *
     * @mbggenerated
     */
    public String getIdPath() {
        return idPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.id_path
     *
     * @param idPath the value for fingerprint.id_path
     *
     * @mbggenerated
     */
    public void setIdPath(String idPath) {
        this.idPath = idPath == null ? null : idPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.remark
     *
     * @return the value of fingerprint.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.remark
     *
     * @param remark the value for fingerprint.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.last_update
     *
     * @return the value of fingerprint.last_update
     *
     * @mbggenerated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.last_update
     *
     * @param lastUpdate the value for fingerprint.last_update
     *
     * @mbggenerated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}