package bean;

public class leaflets {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaflets.leaflets_number
     *
     * @mbggenerated
     */
    private Integer leafletsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaflets.leaflets_chname
     *
     * @mbggenerated
     */
    private String leafletsChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaflets.leaflets_enname
     *
     * @mbggenerated
     */
    private String leafletsEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaflets.leaflets_number
     *
     * @return the value of leaflets.leaflets_number
     *
     * @mbggenerated
     */
    public Integer getLeafletsNumber() {
        return leafletsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaflets.leaflets_number
     *
     * @param leafletsNumber the value for leaflets.leaflets_number
     *
     * @mbggenerated
     */
    public void setLeafletsNumber(Integer leafletsNumber) {
        this.leafletsNumber = leafletsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaflets.leaflets_chname
     *
     * @return the value of leaflets.leaflets_chname
     *
     * @mbggenerated
     */
    public String getLeafletsChname() {
        return leafletsChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaflets.leaflets_chname
     *
     * @param leafletsChname the value for leaflets.leaflets_chname
     *
     * @mbggenerated
     */
    public void setLeafletsChname(String leafletsChname) {
        this.leafletsChname = leafletsChname == null ? null : leafletsChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaflets.leaflets_enname
     *
     * @return the value of leaflets.leaflets_enname
     *
     * @mbggenerated
     */
    public String getLeafletsEnname() {
        return leafletsEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaflets.leaflets_enname
     *
     * @param leafletsEnname the value for leaflets.leaflets_enname
     *
     * @mbggenerated
     */
    public void setLeafletsEnname(String leafletsEnname) {
        this.leafletsEnname = leafletsEnname == null ? null : leafletsEnname.trim();
    }
}