package bean;

public class leafshape {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leafshape.leafshape_number
     *
     * @mbggenerated
     */
    private Integer leafshapeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leafshape.leafshape_chname
     *
     * @mbggenerated
     */
    private String leafshapeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leafshape.leafshape_enname
     *
     * @mbggenerated
     */
    private String leafshapeEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leafshape.leafshape_number
     *
     * @return the value of leafshape.leafshape_number
     *
     * @mbggenerated
     */
    public Integer getLeafshapeNumber() {
        return leafshapeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leafshape.leafshape_number
     *
     * @param leafshapeNumber the value for leafshape.leafshape_number
     *
     * @mbggenerated
     */
    public void setLeafshapeNumber(Integer leafshapeNumber) {
        this.leafshapeNumber = leafshapeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leafshape.leafshape_chname
     *
     * @return the value of leafshape.leafshape_chname
     *
     * @mbggenerated
     */
    public String getLeafshapeChname() {
        return leafshapeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leafshape.leafshape_chname
     *
     * @param leafshapeChname the value for leafshape.leafshape_chname
     *
     * @mbggenerated
     */
    public void setLeafshapeChname(String leafshapeChname) {
        this.leafshapeChname = leafshapeChname == null ? null : leafshapeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leafshape.leafshape_enname
     *
     * @return the value of leafshape.leafshape_enname
     *
     * @mbggenerated
     */
    public String getLeafshapeEnname() {
        return leafshapeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leafshape.leafshape_enname
     *
     * @param leafshapeEnname the value for leafshape.leafshape_enname
     *
     * @mbggenerated
     */
    public void setLeafshapeEnname(String leafshapeEnname) {
        this.leafshapeEnname = leafshapeEnname == null ? null : leafshapeEnname.trim();
    }
}