package bean;

public class leafletsize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leafletsize.leafletsize_number
     *
     * @mbggenerated
     */
    private Integer leafletsizeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leafletsize.leafletsize_chname
     *
     * @mbggenerated
     */
    private String leafletsizeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leafletsize.leafletsize_enname
     *
     * @mbggenerated
     */
    private String leafletsizeEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leafletsize.leafletsize_remark
     *
     * @mbggenerated
     */
    private String leafletsizeRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leafletsize.leafletsize_number
     *
     * @return the value of leafletsize.leafletsize_number
     *
     * @mbggenerated
     */
    public Integer getLeafletsizeNumber() {
        return leafletsizeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leafletsize.leafletsize_number
     *
     * @param leafletsizeNumber the value for leafletsize.leafletsize_number
     *
     * @mbggenerated
     */
    public void setLeafletsizeNumber(Integer leafletsizeNumber) {
        this.leafletsizeNumber = leafletsizeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leafletsize.leafletsize_chname
     *
     * @return the value of leafletsize.leafletsize_chname
     *
     * @mbggenerated
     */
    public String getLeafletsizeChname() {
        return leafletsizeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leafletsize.leafletsize_chname
     *
     * @param leafletsizeChname the value for leafletsize.leafletsize_chname
     *
     * @mbggenerated
     */
    public void setLeafletsizeChname(String leafletsizeChname) {
        this.leafletsizeChname = leafletsizeChname == null ? null : leafletsizeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leafletsize.leafletsize_enname
     *
     * @return the value of leafletsize.leafletsize_enname
     *
     * @mbggenerated
     */
    public String getLeafletsizeEnname() {
        return leafletsizeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leafletsize.leafletsize_enname
     *
     * @param leafletsizeEnname the value for leafletsize.leafletsize_enname
     *
     * @mbggenerated
     */
    public void setLeafletsizeEnname(String leafletsizeEnname) {
        this.leafletsizeEnname = leafletsizeEnname == null ? null : leafletsizeEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leafletsize.leafletsize_remark
     *
     * @return the value of leafletsize.leafletsize_remark
     *
     * @mbggenerated
     */
    public String getLeafletsizeRemark() {
        return leafletsizeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leafletsize.leafletsize_remark
     *
     * @param leafletsizeRemark the value for leafletsize.leafletsize_remark
     *
     * @mbggenerated
     */
    public void setLeafletsizeRemark(String leafletsizeRemark) {
        this.leafletsizeRemark = leafletsizeRemark == null ? null : leafletsizeRemark.trim();
    }
}