package bean;

public class length {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column length.length_number
     *
     * @mbggenerated
     */
    private Integer lengthNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column length.length_chname
     *
     * @mbggenerated
     */
    private String lengthChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column length.length_enname
     *
     * @mbggenerated
     */
    private String lengthEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column length.length_remark
     *
     * @mbggenerated
     */
    private String lengthRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column length.length_number
     *
     * @return the value of length.length_number
     *
     * @mbggenerated
     */
    public Integer getLengthNumber() {
        return lengthNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column length.length_number
     *
     * @param lengthNumber the value for length.length_number
     *
     * @mbggenerated
     */
    public void setLengthNumber(Integer lengthNumber) {
        this.lengthNumber = lengthNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column length.length_chname
     *
     * @return the value of length.length_chname
     *
     * @mbggenerated
     */
    public String getLengthChname() {
        return lengthChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column length.length_chname
     *
     * @param lengthChname the value for length.length_chname
     *
     * @mbggenerated
     */
    public void setLengthChname(String lengthChname) {
        this.lengthChname = lengthChname == null ? null : lengthChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column length.length_enname
     *
     * @return the value of length.length_enname
     *
     * @mbggenerated
     */
    public String getLengthEnname() {
        return lengthEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column length.length_enname
     *
     * @param lengthEnname the value for length.length_enname
     *
     * @mbggenerated
     */
    public void setLengthEnname(String lengthEnname) {
        this.lengthEnname = lengthEnname == null ? null : lengthEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column length.length_remark
     *
     * @return the value of length.length_remark
     *
     * @mbggenerated
     */
    public String getLengthRemark() {
        return lengthRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column length.length_remark
     *
     * @param lengthRemark the value for length.length_remark
     *
     * @mbggenerated
     */
    public void setLengthRemark(String lengthRemark) {
        this.lengthRemark = lengthRemark == null ? null : lengthRemark.trim();
    }
}