package bean;

public class lipoxygenase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lipoxygenase.lipoxygenase_number
     *
     * @mbggenerated
     */
    private Integer lipoxygenaseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lipoxygenase.lipoxygenase_chname
     *
     * @mbggenerated
     */
    private String lipoxygenaseChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lipoxygenase.lipoxygenase_enname
     *
     * @mbggenerated
     */
    private String lipoxygenaseEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lipoxygenase.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lipoxygenase.lipoxygenase_number
     *
     * @return the value of lipoxygenase.lipoxygenase_number
     *
     * @mbggenerated
     */
    public Integer getLipoxygenaseNumber() {
        return lipoxygenaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lipoxygenase.lipoxygenase_number
     *
     * @param lipoxygenaseNumber the value for lipoxygenase.lipoxygenase_number
     *
     * @mbggenerated
     */
    public void setLipoxygenaseNumber(Integer lipoxygenaseNumber) {
        this.lipoxygenaseNumber = lipoxygenaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lipoxygenase.lipoxygenase_chname
     *
     * @return the value of lipoxygenase.lipoxygenase_chname
     *
     * @mbggenerated
     */
    public String getLipoxygenaseChname() {
        return lipoxygenaseChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lipoxygenase.lipoxygenase_chname
     *
     * @param lipoxygenaseChname the value for lipoxygenase.lipoxygenase_chname
     *
     * @mbggenerated
     */
    public void setLipoxygenaseChname(String lipoxygenaseChname) {
        this.lipoxygenaseChname = lipoxygenaseChname == null ? null : lipoxygenaseChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lipoxygenase.lipoxygenase_enname
     *
     * @return the value of lipoxygenase.lipoxygenase_enname
     *
     * @mbggenerated
     */
    public String getLipoxygenaseEnname() {
        return lipoxygenaseEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lipoxygenase.lipoxygenase_enname
     *
     * @param lipoxygenaseEnname the value for lipoxygenase.lipoxygenase_enname
     *
     * @mbggenerated
     */
    public void setLipoxygenaseEnname(String lipoxygenaseEnname) {
        this.lipoxygenaseEnname = lipoxygenaseEnname == null ? null : lipoxygenaseEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lipoxygenase.remark
     *
     * @return the value of lipoxygenase.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lipoxygenase.remark
     *
     * @param remark the value for lipoxygenase.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}