package bean;

public class organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_id
     *
     * @mbggenerated
     */
    private Integer organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_number
     *
     * @mbggenerated
     */
    private String organizationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_name
     *
     * @mbggenerated
     */
    private String organizationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_address
     *
     * @mbggenerated
     */
    private String organizationAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_phone
     *
     * @mbggenerated
     */
    private String organizationPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_contact
     *
     * @mbggenerated
     */
    private String organizationContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_mobilephone
     *
     * @mbggenerated
     */
    private String organizationMobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_id
     *
     * @return the value of organization.organization_id
     *
     * @mbggenerated
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_id
     *
     * @param organizationId the value for organization.organization_id
     *
     * @mbggenerated
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_number
     *
     * @return the value of organization.organization_number
     *
     * @mbggenerated
     */
    public String getOrganizationNumber() {
        return organizationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_number
     *
     * @param organizationNumber the value for organization.organization_number
     *
     * @mbggenerated
     */
    public void setOrganizationNumber(String organizationNumber) {
        this.organizationNumber = organizationNumber == null ? null : organizationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_name
     *
     * @return the value of organization.organization_name
     *
     * @mbggenerated
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_name
     *
     * @param organizationName the value for organization.organization_name
     *
     * @mbggenerated
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_address
     *
     * @return the value of organization.organization_address
     *
     * @mbggenerated
     */
    public String getOrganizationAddress() {
        return organizationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_address
     *
     * @param organizationAddress the value for organization.organization_address
     *
     * @mbggenerated
     */
    public void setOrganizationAddress(String organizationAddress) {
        this.organizationAddress = organizationAddress == null ? null : organizationAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_phone
     *
     * @return the value of organization.organization_phone
     *
     * @mbggenerated
     */
    public String getOrganizationPhone() {
        return organizationPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_phone
     *
     * @param organizationPhone the value for organization.organization_phone
     *
     * @mbggenerated
     */
    public void setOrganizationPhone(String organizationPhone) {
        this.organizationPhone = organizationPhone == null ? null : organizationPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_contact
     *
     * @return the value of organization.organization_contact
     *
     * @mbggenerated
     */
    public String getOrganizationContact() {
        return organizationContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_contact
     *
     * @param organizationContact the value for organization.organization_contact
     *
     * @mbggenerated
     */
    public void setOrganizationContact(String organizationContact) {
        this.organizationContact = organizationContact == null ? null : organizationContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_mobilephone
     *
     * @return the value of organization.organization_mobilephone
     *
     * @mbggenerated
     */
    public String getOrganizationMobilephone() {
        return organizationMobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_mobilephone
     *
     * @param organizationMobilephone the value for organization.organization_mobilephone
     *
     * @mbggenerated
     */
    public void setOrganizationMobilephone(String organizationMobilephone) {
        this.organizationMobilephone = organizationMobilephone == null ? null : organizationMobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.remark
     *
     * @return the value of organization.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.remark
     *
     * @param remark the value for organization.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}