package bean;

public class planttype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planttype.planttype_number
     *
     * @mbggenerated
     */
    private Integer planttypeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planttype.planttype_chname
     *
     * @mbggenerated
     */
    private String planttypeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planttype.planttype_enname
     *
     * @mbggenerated
     */
    private String planttypeEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planttype.planttype_remark
     *
     * @mbggenerated
     */
    private String planttypeRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planttype.planttype_number
     *
     * @return the value of planttype.planttype_number
     *
     * @mbggenerated
     */
    public Integer getPlanttypeNumber() {
        return planttypeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planttype.planttype_number
     *
     * @param planttypeNumber the value for planttype.planttype_number
     *
     * @mbggenerated
     */
    public void setPlanttypeNumber(Integer planttypeNumber) {
        this.planttypeNumber = planttypeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planttype.planttype_chname
     *
     * @return the value of planttype.planttype_chname
     *
     * @mbggenerated
     */
    public String getPlanttypeChname() {
        return planttypeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planttype.planttype_chname
     *
     * @param planttypeChname the value for planttype.planttype_chname
     *
     * @mbggenerated
     */
    public void setPlanttypeChname(String planttypeChname) {
        this.planttypeChname = planttypeChname == null ? null : planttypeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planttype.planttype_enname
     *
     * @return the value of planttype.planttype_enname
     *
     * @mbggenerated
     */
    public String getPlanttypeEnname() {
        return planttypeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planttype.planttype_enname
     *
     * @param planttypeEnname the value for planttype.planttype_enname
     *
     * @mbggenerated
     */
    public void setPlanttypeEnname(String planttypeEnname) {
        this.planttypeEnname = planttypeEnname == null ? null : planttypeEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planttype.planttype_remark
     *
     * @return the value of planttype.planttype_remark
     *
     * @mbggenerated
     */
    public String getPlanttypeRemark() {
        return planttypeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planttype.planttype_remark
     *
     * @param planttypeRemark the value for planttype.planttype_remark
     *
     * @mbggenerated
     */
    public void setPlanttypeRemark(String planttypeRemark) {
        this.planttypeRemark = planttypeRemark == null ? null : planttypeRemark.trim();
    }
}