package bean;

public class podshape {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column podshape.podshape_number
     *
     * @mbggenerated
     */
    private Integer podshapeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column podshape.podshape_chname
     *
     * @mbggenerated
     */
    private String podshapeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column podshape.podshape_enname
     *
     * @mbggenerated
     */
    private String podshapeEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column podshape.podshape_number
     *
     * @return the value of podshape.podshape_number
     *
     * @mbggenerated
     */
    public Integer getPodshapeNumber() {
        return podshapeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column podshape.podshape_number
     *
     * @param podshapeNumber the value for podshape.podshape_number
     *
     * @mbggenerated
     */
    public void setPodshapeNumber(Integer podshapeNumber) {
        this.podshapeNumber = podshapeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column podshape.podshape_chname
     *
     * @return the value of podshape.podshape_chname
     *
     * @mbggenerated
     */
    public String getPodshapeChname() {
        return podshapeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column podshape.podshape_chname
     *
     * @param podshapeChname the value for podshape.podshape_chname
     *
     * @mbggenerated
     */
    public void setPodshapeChname(String podshapeChname) {
        this.podshapeChname = podshapeChname == null ? null : podshapeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column podshape.podshape_enname
     *
     * @return the value of podshape.podshape_enname
     *
     * @mbggenerated
     */
    public String getPodshapeEnname() {
        return podshapeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column podshape.podshape_enname
     *
     * @param podshapeEnname the value for podshape.podshape_enname
     *
     * @mbggenerated
     */
    public void setPodshapeEnname(String podshapeEnname) {
        this.podshapeEnname = podshapeEnname == null ? null : podshapeEnname.trim();
    }
}