package bean;

public class podsize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column podsize.podsize_number
     *
     * @mbggenerated
     */
    private Integer podsizeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column podsize.podsize_chname
     *
     * @mbggenerated
     */
    private String podsizeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column podsize.podsize_enname
     *
     * @mbggenerated
     */
    private String podsizeEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column podsize.podsize_remark
     *
     * @mbggenerated
     */
    private String podsizeRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column podsize.podsize_number
     *
     * @return the value of podsize.podsize_number
     *
     * @mbggenerated
     */
    public Integer getPodsizeNumber() {
        return podsizeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column podsize.podsize_number
     *
     * @param podsizeNumber the value for podsize.podsize_number
     *
     * @mbggenerated
     */
    public void setPodsizeNumber(Integer podsizeNumber) {
        this.podsizeNumber = podsizeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column podsize.podsize_chname
     *
     * @return the value of podsize.podsize_chname
     *
     * @mbggenerated
     */
    public String getPodsizeChname() {
        return podsizeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column podsize.podsize_chname
     *
     * @param podsizeChname the value for podsize.podsize_chname
     *
     * @mbggenerated
     */
    public void setPodsizeChname(String podsizeChname) {
        this.podsizeChname = podsizeChname == null ? null : podsizeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column podsize.podsize_enname
     *
     * @return the value of podsize.podsize_enname
     *
     * @mbggenerated
     */
    public String getPodsizeEnname() {
        return podsizeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column podsize.podsize_enname
     *
     * @param podsizeEnname the value for podsize.podsize_enname
     *
     * @mbggenerated
     */
    public void setPodsizeEnname(String podsizeEnname) {
        this.podsizeEnname = podsizeEnname == null ? null : podsizeEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column podsize.podsize_remark
     *
     * @return the value of podsize.podsize_remark
     *
     * @mbggenerated
     */
    public String getPodsizeRemark() {
        return podsizeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column podsize.podsize_remark
     *
     * @param podsizeRemark the value for podsize.podsize_remark
     *
     * @mbggenerated
     */
    public void setPodsizeRemark(String podsizeRemark) {
        this.podsizeRemark = podsizeRemark == null ? null : podsizeRemark.trim();
    }
}