package bean;

public class province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.province_number
     *
     * @mbggenerated
     */
    private Integer provinceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.province_chnumber
     *
     * @mbggenerated
     */
    private String provinceChnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.province_ennumber
     *
     * @mbggenerated
     */
    private String provinceEnnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.province_number
     *
     * @return the value of province.province_number
     *
     * @mbggenerated
     */
    public Integer getProvinceNumber() {
        return provinceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.province_number
     *
     * @param provinceNumber the value for province.province_number
     *
     * @mbggenerated
     */
    public void setProvinceNumber(Integer provinceNumber) {
        this.provinceNumber = provinceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.province_chnumber
     *
     * @return the value of province.province_chnumber
     *
     * @mbggenerated
     */
    public String getProvinceChnumber() {
        return provinceChnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.province_chnumber
     *
     * @param provinceChnumber the value for province.province_chnumber
     *
     * @mbggenerated
     */
    public void setProvinceChnumber(String provinceChnumber) {
        this.provinceChnumber = provinceChnumber == null ? null : provinceChnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.province_ennumber
     *
     * @return the value of province.province_ennumber
     *
     * @mbggenerated
     */
    public String getProvinceEnnumber() {
        return provinceEnnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.province_ennumber
     *
     * @param provinceEnnumber the value for province.province_ennumber
     *
     * @mbggenerated
     */
    public void setProvinceEnnumber(String provinceEnnumber) {
        this.provinceEnnumber = provinceEnnumber == null ? null : provinceEnnumber.trim();
    }
}