package bean;

public class pubescencetype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubescencetype.pubescencetype_number
     *
     * @mbggenerated
     */
    private Integer pubescencetypeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubescencetype.pubescencetype_chname
     *
     * @mbggenerated
     */
    private String pubescencetypeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubescencetype.pubescencetype_enname
     *
     * @mbggenerated
     */
    private String pubescencetypeEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubescencetype.pubescencetype_number
     *
     * @return the value of pubescencetype.pubescencetype_number
     *
     * @mbggenerated
     */
    public Integer getPubescencetypeNumber() {
        return pubescencetypeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubescencetype.pubescencetype_number
     *
     * @param pubescencetypeNumber the value for pubescencetype.pubescencetype_number
     *
     * @mbggenerated
     */
    public void setPubescencetypeNumber(Integer pubescencetypeNumber) {
        this.pubescencetypeNumber = pubescencetypeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubescencetype.pubescencetype_chname
     *
     * @return the value of pubescencetype.pubescencetype_chname
     *
     * @mbggenerated
     */
    public String getPubescencetypeChname() {
        return pubescencetypeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubescencetype.pubescencetype_chname
     *
     * @param pubescencetypeChname the value for pubescencetype.pubescencetype_chname
     *
     * @mbggenerated
     */
    public void setPubescencetypeChname(String pubescencetypeChname) {
        this.pubescencetypeChname = pubescencetypeChname == null ? null : pubescencetypeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubescencetype.pubescencetype_enname
     *
     * @return the value of pubescencetype.pubescencetype_enname
     *
     * @mbggenerated
     */
    public String getPubescencetypeEnname() {
        return pubescencetypeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubescencetype.pubescencetype_enname
     *
     * @param pubescencetypeEnname the value for pubescencetype.pubescencetype_enname
     *
     * @mbggenerated
     */
    public void setPubescencetypeEnname(String pubescencetypeEnname) {
        this.pubescencetypeEnname = pubescencetypeEnname == null ? null : pubescencetypeEnname.trim();
    }
}