package bean;

public class pubescencedensity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubescencedensity.pubescencedensity_number
     *
     * @mbggenerated
     */
    private Integer pubescencedensityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubescencedensity.pubescencedensity_chname
     *
     * @mbggenerated
     */
    private String pubescencedensityChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubescencedensity.pubescencedensity_enname
     *
     * @mbggenerated
     */
    private String pubescencedensityEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubescencedensity.pubescencedensity_number
     *
     * @return the value of pubescencedensity.pubescencedensity_number
     *
     * @mbggenerated
     */
    public Integer getPubescencedensityNumber() {
        return pubescencedensityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubescencedensity.pubescencedensity_number
     *
     * @param pubescencedensityNumber the value for pubescencedensity.pubescencedensity_number
     *
     * @mbggenerated
     */
    public void setPubescencedensityNumber(Integer pubescencedensityNumber) {
        this.pubescencedensityNumber = pubescencedensityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubescencedensity.pubescencedensity_chname
     *
     * @return the value of pubescencedensity.pubescencedensity_chname
     *
     * @mbggenerated
     */
    public String getPubescencedensityChname() {
        return pubescencedensityChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubescencedensity.pubescencedensity_chname
     *
     * @param pubescencedensityChname the value for pubescencedensity.pubescencedensity_chname
     *
     * @mbggenerated
     */
    public void setPubescencedensityChname(String pubescencedensityChname) {
        this.pubescencedensityChname = pubescencedensityChname == null ? null : pubescencedensityChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubescencedensity.pubescencedensity_enname
     *
     * @return the value of pubescencedensity.pubescencedensity_enname
     *
     * @mbggenerated
     */
    public String getPubescencedensityEnname() {
        return pubescencedensityEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubescencedensity.pubescencedensity_enname
     *
     * @param pubescencedensityEnname the value for pubescencedensity.pubescencedensity_enname
     *
     * @mbggenerated
     */
    public void setPubescencedensityEnname(String pubescencedensityEnname) {
        this.pubescencedensityEnname = pubescencedensityEnname == null ? null : pubescencedensityEnname.trim();
    }
}