package bean;

public class seedsize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedsize.seedsize_number
     *
     * @mbggenerated
     */
    private Integer seedsizeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedsize.seedsize_chname
     *
     * @mbggenerated
     */
    private String seedsizeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedsize.seedsize_enname
     *
     * @mbggenerated
     */
    private String seedsizeEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedsize.seedsize_remark
     *
     * @mbggenerated
     */
    private String seedsizeRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedsize.seedsize_number
     *
     * @return the value of seedsize.seedsize_number
     *
     * @mbggenerated
     */
    public Integer getSeedsizeNumber() {
        return seedsizeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedsize.seedsize_number
     *
     * @param seedsizeNumber the value for seedsize.seedsize_number
     *
     * @mbggenerated
     */
    public void setSeedsizeNumber(Integer seedsizeNumber) {
        this.seedsizeNumber = seedsizeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedsize.seedsize_chname
     *
     * @return the value of seedsize.seedsize_chname
     *
     * @mbggenerated
     */
    public String getSeedsizeChname() {
        return seedsizeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedsize.seedsize_chname
     *
     * @param seedsizeChname the value for seedsize.seedsize_chname
     *
     * @mbggenerated
     */
    public void setSeedsizeChname(String seedsizeChname) {
        this.seedsizeChname = seedsizeChname == null ? null : seedsizeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedsize.seedsize_enname
     *
     * @return the value of seedsize.seedsize_enname
     *
     * @mbggenerated
     */
    public String getSeedsizeEnname() {
        return seedsizeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedsize.seedsize_enname
     *
     * @param seedsizeEnname the value for seedsize.seedsize_enname
     *
     * @mbggenerated
     */
    public void setSeedsizeEnname(String seedsizeEnname) {
        this.seedsizeEnname = seedsizeEnname == null ? null : seedsizeEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedsize.seedsize_remark
     *
     * @return the value of seedsize.seedsize_remark
     *
     * @mbggenerated
     */
    public String getSeedsizeRemark() {
        return seedsizeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedsize.seedsize_remark
     *
     * @param seedsizeRemark the value for seedsize.seedsize_remark
     *
     * @mbggenerated
     */
    public void setSeedsizeRemark(String seedsizeRemark) {
        this.seedsizeRemark = seedsizeRemark == null ? null : seedsizeRemark.trim();
    }
}