package bean;

public class seedcoatluster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedcoatluster.seedcoatluster_number
     *
     * @mbggenerated
     */
    private Integer seedcoatlusterNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedcoatluster.seedcoatluster_chname
     *
     * @mbggenerated
     */
    private String seedcoatlusterChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seedcoatluster.seedcoatluster_enname
     *
     * @mbggenerated
     */
    private String seedcoatlusterEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedcoatluster.seedcoatluster_number
     *
     * @return the value of seedcoatluster.seedcoatluster_number
     *
     * @mbggenerated
     */
    public Integer getSeedcoatlusterNumber() {
        return seedcoatlusterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedcoatluster.seedcoatluster_number
     *
     * @param seedcoatlusterNumber the value for seedcoatluster.seedcoatluster_number
     *
     * @mbggenerated
     */
    public void setSeedcoatlusterNumber(Integer seedcoatlusterNumber) {
        this.seedcoatlusterNumber = seedcoatlusterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedcoatluster.seedcoatluster_chname
     *
     * @return the value of seedcoatluster.seedcoatluster_chname
     *
     * @mbggenerated
     */
    public String getSeedcoatlusterChname() {
        return seedcoatlusterChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedcoatluster.seedcoatluster_chname
     *
     * @param seedcoatlusterChname the value for seedcoatluster.seedcoatluster_chname
     *
     * @mbggenerated
     */
    public void setSeedcoatlusterChname(String seedcoatlusterChname) {
        this.seedcoatlusterChname = seedcoatlusterChname == null ? null : seedcoatlusterChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seedcoatluster.seedcoatluster_enname
     *
     * @return the value of seedcoatluster.seedcoatluster_enname
     *
     * @mbggenerated
     */
    public String getSeedcoatlusterEnname() {
        return seedcoatlusterEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seedcoatluster.seedcoatluster_enname
     *
     * @param seedcoatlusterEnname the value for seedcoatluster.seedcoatluster_enname
     *
     * @mbggenerated
     */
    public void setSeedcoatlusterEnname(String seedcoatlusterEnname) {
        this.seedcoatlusterEnname = seedcoatlusterEnname == null ? null : seedcoatlusterEnname.trim();
    }
}