package bean;

public class site {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.site_number
     *
     * @mbggenerated
     */
    private Integer siteNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.site_chnumber
     *
     * @mbggenerated
     */
    private String siteChnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.site_ennumber
     *
     * @mbggenerated
     */
    private String siteEnnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.site_number
     *
     * @return the value of site.site_number
     *
     * @mbggenerated
     */
    public Integer getSiteNumber() {
        return siteNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.site_number
     *
     * @param siteNumber the value for site.site_number
     *
     * @mbggenerated
     */
    public void setSiteNumber(Integer siteNumber) {
        this.siteNumber = siteNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.site_chnumber
     *
     * @return the value of site.site_chnumber
     *
     * @mbggenerated
     */
    public String getSiteChnumber() {
        return siteChnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.site_chnumber
     *
     * @param siteChnumber the value for site.site_chnumber
     *
     * @mbggenerated
     */
    public void setSiteChnumber(String siteChnumber) {
        this.siteChnumber = siteChnumber == null ? null : siteChnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.site_ennumber
     *
     * @return the value of site.site_ennumber
     *
     * @mbggenerated
     */
    public String getSiteEnnumber() {
        return siteEnnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.site_ennumber
     *
     * @param siteEnnumber the value for site.site_ennumber
     *
     * @mbggenerated
     */
    public void setSiteEnnumber(String siteEnnumber) {
        this.siteEnnumber = siteEnnumber == null ? null : siteEnnumber.trim();
    }
}