package bean;

public class stemshape {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stemshape.stemshape_number
     *
     * @mbggenerated
     */
    private Integer stemshapeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stemshape.stemshape_chname
     *
     * @mbggenerated
     */
    private String stemshapeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stemshape.stemshape_enname
     *
     * @mbggenerated
     */
    private String stemshapeEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stemshape.stemshape_remark
     *
     * @mbggenerated
     */
    private String stemshapeRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stemshape.stemshape_number
     *
     * @return the value of stemshape.stemshape_number
     *
     * @mbggenerated
     */
    public Integer getStemshapeNumber() {
        return stemshapeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stemshape.stemshape_number
     *
     * @param stemshapeNumber the value for stemshape.stemshape_number
     *
     * @mbggenerated
     */
    public void setStemshapeNumber(Integer stemshapeNumber) {
        this.stemshapeNumber = stemshapeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stemshape.stemshape_chname
     *
     * @return the value of stemshape.stemshape_chname
     *
     * @mbggenerated
     */
    public String getStemshapeChname() {
        return stemshapeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stemshape.stemshape_chname
     *
     * @param stemshapeChname the value for stemshape.stemshape_chname
     *
     * @mbggenerated
     */
    public void setStemshapeChname(String stemshapeChname) {
        this.stemshapeChname = stemshapeChname == null ? null : stemshapeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stemshape.stemshape_enname
     *
     * @return the value of stemshape.stemshape_enname
     *
     * @mbggenerated
     */
    public String getStemshapeEnname() {
        return stemshapeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stemshape.stemshape_enname
     *
     * @param stemshapeEnname the value for stemshape.stemshape_enname
     *
     * @mbggenerated
     */
    public void setStemshapeEnname(String stemshapeEnname) {
        this.stemshapeEnname = stemshapeEnname == null ? null : stemshapeEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stemshape.stemshape_remark
     *
     * @return the value of stemshape.stemshape_remark
     *
     * @mbggenerated
     */
    public String getStemshapeRemark() {
        return stemshapeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stemshape.stemshape_remark
     *
     * @param stemshapeRemark the value for stemshape.stemshape_remark
     *
     * @mbggenerated
     */
    public void setStemshapeRemark(String stemshapeRemark) {
        this.stemshapeRemark = stemshapeRemark == null ? null : stemshapeRemark.trim();
    }
}