package bean;

import java.util.Date;

public class toleranceresistant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.toleranceresistant_number
     *
     * @mbggenerated
     */
    private String toleranceresistantNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.lipoxygenase_chname
     *
     * @mbggenerated
     */
    private String lipoxygenaseChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.tsaltsprout_chname
     *
     * @mbggenerated
     */
    private String tsaltsproutChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.tsaltseedling_chname
     *
     * @mbggenerated
     */
    private String tsaltseedlingChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.tsaltadult_chname
     *
     * @mbggenerated
     */
    private String tsaltadultChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.tdrosprout_chname
     *
     * @mbggenerated
     */
    private String tdrosproutChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.tdroadult_chname
     *
     * @mbggenerated
     */
    private String tdroadultChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.tcoldsprout_chname
     *
     * @mbggenerated
     */
    private String tcoldsproutChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.taluminum_chname
     *
     * @mbggenerated
     */
    private String taluminumChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.tacidrain_chname
     *
     * @mbggenerated
     */
    private String tacidrainChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rrust_chname
     *
     * @mbggenerated
     */
    private String rrustChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rfrogeyeleafspot_chname
     *
     * @mbggenerated
     */
    private String rfrogeyeleafspotChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rdownymildew_chname
     *
     * @mbggenerated
     */
    private String rdownymildewChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rpurpleseedstain_chname
     *
     * @mbggenerated
     */
    private String rpurpleseedstainChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rbacterialblight_chname
     *
     * @mbggenerated
     */
    private String rbacterialblightChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rmosaicvirus_chname
     *
     * @mbggenerated
     */
    private String rmosaicvirusChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rphytophthorarootrot_chname
     *
     * @mbggenerated
     */
    private String rphytophthorarootrotChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rcystnematode_chname
     *
     * @mbggenerated
     */
    private String rcystnematodeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rpodborer_chname
     *
     * @mbggenerated
     */
    private String rpodborerChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.raphid_chname
     *
     * @mbggenerated
     */
    private String raphidChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rmarucatestulalisgeyer_chname
     *
     * @mbggenerated
     */
    private String rmarucatestulalisgeyerChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.ragromyidfly_chname
     *
     * @mbggenerated
     */
    private String ragromyidflyChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rleaffeedinginsect_chname
     *
     * @mbggenerated
     */
    private String rleaffeedinginsectChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toleranceresistant.rlast_update
     *
     * @mbggenerated
     */
    private Date rlastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.toleranceresistant_number
     *
     * @return the value of toleranceresistant.toleranceresistant_number
     *
     * @mbggenerated
     */
    public String getToleranceresistantNumber() {
        return toleranceresistantNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.toleranceresistant_number
     *
     * @param toleranceresistantNumber the value for toleranceresistant.toleranceresistant_number
     *
     * @mbggenerated
     */
    public void setToleranceresistantNumber(String toleranceresistantNumber) {
        this.toleranceresistantNumber = toleranceresistantNumber == null ? null : toleranceresistantNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.lipoxygenase_chname
     *
     * @return the value of toleranceresistant.lipoxygenase_chname
     *
     * @mbggenerated
     */
    public String getLipoxygenaseChname() {
        return lipoxygenaseChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.lipoxygenase_chname
     *
     * @param lipoxygenaseChname the value for toleranceresistant.lipoxygenase_chname
     *
     * @mbggenerated
     */
    public void setLipoxygenaseChname(String lipoxygenaseChname) {
        this.lipoxygenaseChname = lipoxygenaseChname == null ? null : lipoxygenaseChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.tsaltsprout_chname
     *
     * @return the value of toleranceresistant.tsaltsprout_chname
     *
     * @mbggenerated
     */
    public String getTsaltsproutChname() {
        return tsaltsproutChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.tsaltsprout_chname
     *
     * @param tsaltsproutChname the value for toleranceresistant.tsaltsprout_chname
     *
     * @mbggenerated
     */
    public void setTsaltsproutChname(String tsaltsproutChname) {
        this.tsaltsproutChname = tsaltsproutChname == null ? null : tsaltsproutChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.tsaltseedling_chname
     *
     * @return the value of toleranceresistant.tsaltseedling_chname
     *
     * @mbggenerated
     */
    public String getTsaltseedlingChname() {
        return tsaltseedlingChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.tsaltseedling_chname
     *
     * @param tsaltseedlingChname the value for toleranceresistant.tsaltseedling_chname
     *
     * @mbggenerated
     */
    public void setTsaltseedlingChname(String tsaltseedlingChname) {
        this.tsaltseedlingChname = tsaltseedlingChname == null ? null : tsaltseedlingChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.tsaltadult_chname
     *
     * @return the value of toleranceresistant.tsaltadult_chname
     *
     * @mbggenerated
     */
    public String getTsaltadultChname() {
        return tsaltadultChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.tsaltadult_chname
     *
     * @param tsaltadultChname the value for toleranceresistant.tsaltadult_chname
     *
     * @mbggenerated
     */
    public void setTsaltadultChname(String tsaltadultChname) {
        this.tsaltadultChname = tsaltadultChname == null ? null : tsaltadultChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.tdrosprout_chname
     *
     * @return the value of toleranceresistant.tdrosprout_chname
     *
     * @mbggenerated
     */
    public String getTdrosproutChname() {
        return tdrosproutChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.tdrosprout_chname
     *
     * @param tdrosproutChname the value for toleranceresistant.tdrosprout_chname
     *
     * @mbggenerated
     */
    public void setTdrosproutChname(String tdrosproutChname) {
        this.tdrosproutChname = tdrosproutChname == null ? null : tdrosproutChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.tdroadult_chname
     *
     * @return the value of toleranceresistant.tdroadult_chname
     *
     * @mbggenerated
     */
    public String getTdroadultChname() {
        return tdroadultChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.tdroadult_chname
     *
     * @param tdroadultChname the value for toleranceresistant.tdroadult_chname
     *
     * @mbggenerated
     */
    public void setTdroadultChname(String tdroadultChname) {
        this.tdroadultChname = tdroadultChname == null ? null : tdroadultChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.tcoldsprout_chname
     *
     * @return the value of toleranceresistant.tcoldsprout_chname
     *
     * @mbggenerated
     */
    public String getTcoldsproutChname() {
        return tcoldsproutChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.tcoldsprout_chname
     *
     * @param tcoldsproutChname the value for toleranceresistant.tcoldsprout_chname
     *
     * @mbggenerated
     */
    public void setTcoldsproutChname(String tcoldsproutChname) {
        this.tcoldsproutChname = tcoldsproutChname == null ? null : tcoldsproutChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.taluminum_chname
     *
     * @return the value of toleranceresistant.taluminum_chname
     *
     * @mbggenerated
     */
    public String getTaluminumChname() {
        return taluminumChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.taluminum_chname
     *
     * @param taluminumChname the value for toleranceresistant.taluminum_chname
     *
     * @mbggenerated
     */
    public void setTaluminumChname(String taluminumChname) {
        this.taluminumChname = taluminumChname == null ? null : taluminumChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.tacidrain_chname
     *
     * @return the value of toleranceresistant.tacidrain_chname
     *
     * @mbggenerated
     */
    public String getTacidrainChname() {
        return tacidrainChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.tacidrain_chname
     *
     * @param tacidrainChname the value for toleranceresistant.tacidrain_chname
     *
     * @mbggenerated
     */
    public void setTacidrainChname(String tacidrainChname) {
        this.tacidrainChname = tacidrainChname == null ? null : tacidrainChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rrust_chname
     *
     * @return the value of toleranceresistant.rrust_chname
     *
     * @mbggenerated
     */
    public String getRrustChname() {
        return rrustChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rrust_chname
     *
     * @param rrustChname the value for toleranceresistant.rrust_chname
     *
     * @mbggenerated
     */
    public void setRrustChname(String rrustChname) {
        this.rrustChname = rrustChname == null ? null : rrustChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rfrogeyeleafspot_chname
     *
     * @return the value of toleranceresistant.rfrogeyeleafspot_chname
     *
     * @mbggenerated
     */
    public String getRfrogeyeleafspotChname() {
        return rfrogeyeleafspotChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rfrogeyeleafspot_chname
     *
     * @param rfrogeyeleafspotChname the value for toleranceresistant.rfrogeyeleafspot_chname
     *
     * @mbggenerated
     */
    public void setRfrogeyeleafspotChname(String rfrogeyeleafspotChname) {
        this.rfrogeyeleafspotChname = rfrogeyeleafspotChname == null ? null : rfrogeyeleafspotChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rdownymildew_chname
     *
     * @return the value of toleranceresistant.rdownymildew_chname
     *
     * @mbggenerated
     */
    public String getRdownymildewChname() {
        return rdownymildewChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rdownymildew_chname
     *
     * @param rdownymildewChname the value for toleranceresistant.rdownymildew_chname
     *
     * @mbggenerated
     */
    public void setRdownymildewChname(String rdownymildewChname) {
        this.rdownymildewChname = rdownymildewChname == null ? null : rdownymildewChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rpurpleseedstain_chname
     *
     * @return the value of toleranceresistant.rpurpleseedstain_chname
     *
     * @mbggenerated
     */
    public String getRpurpleseedstainChname() {
        return rpurpleseedstainChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rpurpleseedstain_chname
     *
     * @param rpurpleseedstainChname the value for toleranceresistant.rpurpleseedstain_chname
     *
     * @mbggenerated
     */
    public void setRpurpleseedstainChname(String rpurpleseedstainChname) {
        this.rpurpleseedstainChname = rpurpleseedstainChname == null ? null : rpurpleseedstainChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rbacterialblight_chname
     *
     * @return the value of toleranceresistant.rbacterialblight_chname
     *
     * @mbggenerated
     */
    public String getRbacterialblightChname() {
        return rbacterialblightChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rbacterialblight_chname
     *
     * @param rbacterialblightChname the value for toleranceresistant.rbacterialblight_chname
     *
     * @mbggenerated
     */
    public void setRbacterialblightChname(String rbacterialblightChname) {
        this.rbacterialblightChname = rbacterialblightChname == null ? null : rbacterialblightChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rmosaicvirus_chname
     *
     * @return the value of toleranceresistant.rmosaicvirus_chname
     *
     * @mbggenerated
     */
    public String getRmosaicvirusChname() {
        return rmosaicvirusChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rmosaicvirus_chname
     *
     * @param rmosaicvirusChname the value for toleranceresistant.rmosaicvirus_chname
     *
     * @mbggenerated
     */
    public void setRmosaicvirusChname(String rmosaicvirusChname) {
        this.rmosaicvirusChname = rmosaicvirusChname == null ? null : rmosaicvirusChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rphytophthorarootrot_chname
     *
     * @return the value of toleranceresistant.rphytophthorarootrot_chname
     *
     * @mbggenerated
     */
    public String getRphytophthorarootrotChname() {
        return rphytophthorarootrotChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rphytophthorarootrot_chname
     *
     * @param rphytophthorarootrotChname the value for toleranceresistant.rphytophthorarootrot_chname
     *
     * @mbggenerated
     */
    public void setRphytophthorarootrotChname(String rphytophthorarootrotChname) {
        this.rphytophthorarootrotChname = rphytophthorarootrotChname == null ? null : rphytophthorarootrotChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rcystnematode_chname
     *
     * @return the value of toleranceresistant.rcystnematode_chname
     *
     * @mbggenerated
     */
    public String getRcystnematodeChname() {
        return rcystnematodeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rcystnematode_chname
     *
     * @param rcystnematodeChname the value for toleranceresistant.rcystnematode_chname
     *
     * @mbggenerated
     */
    public void setRcystnematodeChname(String rcystnematodeChname) {
        this.rcystnematodeChname = rcystnematodeChname == null ? null : rcystnematodeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rpodborer_chname
     *
     * @return the value of toleranceresistant.rpodborer_chname
     *
     * @mbggenerated
     */
    public String getRpodborerChname() {
        return rpodborerChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rpodborer_chname
     *
     * @param rpodborerChname the value for toleranceresistant.rpodborer_chname
     *
     * @mbggenerated
     */
    public void setRpodborerChname(String rpodborerChname) {
        this.rpodborerChname = rpodborerChname == null ? null : rpodborerChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.raphid_chname
     *
     * @return the value of toleranceresistant.raphid_chname
     *
     * @mbggenerated
     */
    public String getRaphidChname() {
        return raphidChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.raphid_chname
     *
     * @param raphidChname the value for toleranceresistant.raphid_chname
     *
     * @mbggenerated
     */
    public void setRaphidChname(String raphidChname) {
        this.raphidChname = raphidChname == null ? null : raphidChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rmarucatestulalisgeyer_chname
     *
     * @return the value of toleranceresistant.rmarucatestulalisgeyer_chname
     *
     * @mbggenerated
     */
    public String getRmarucatestulalisgeyerChname() {
        return rmarucatestulalisgeyerChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rmarucatestulalisgeyer_chname
     *
     * @param rmarucatestulalisgeyerChname the value for toleranceresistant.rmarucatestulalisgeyer_chname
     *
     * @mbggenerated
     */
    public void setRmarucatestulalisgeyerChname(String rmarucatestulalisgeyerChname) {
        this.rmarucatestulalisgeyerChname = rmarucatestulalisgeyerChname == null ? null : rmarucatestulalisgeyerChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.ragromyidfly_chname
     *
     * @return the value of toleranceresistant.ragromyidfly_chname
     *
     * @mbggenerated
     */
    public String getRagromyidflyChname() {
        return ragromyidflyChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.ragromyidfly_chname
     *
     * @param ragromyidflyChname the value for toleranceresistant.ragromyidfly_chname
     *
     * @mbggenerated
     */
    public void setRagromyidflyChname(String ragromyidflyChname) {
        this.ragromyidflyChname = ragromyidflyChname == null ? null : ragromyidflyChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rleaffeedinginsect_chname
     *
     * @return the value of toleranceresistant.rleaffeedinginsect_chname
     *
     * @mbggenerated
     */
    public String getRleaffeedinginsectChname() {
        return rleaffeedinginsectChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rleaffeedinginsect_chname
     *
     * @param rleaffeedinginsectChname the value for toleranceresistant.rleaffeedinginsect_chname
     *
     * @mbggenerated
     */
    public void setRleaffeedinginsectChname(String rleaffeedinginsectChname) {
        this.rleaffeedinginsectChname = rleaffeedinginsectChname == null ? null : rleaffeedinginsectChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toleranceresistant.rlast_update
     *
     * @return the value of toleranceresistant.rlast_update
     *
     * @mbggenerated
     */
    public Date getRlastUpdate() {
        return rlastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toleranceresistant.rlast_update
     *
     * @param rlastUpdate the value for toleranceresistant.rlast_update
     *
     * @mbggenerated
     */
    public void setRlastUpdate(Date rlastUpdate) {
        this.rlastUpdate = rlastUpdate;
    }
}