package bean;

public class usagetype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usagetype.usagetype_number
     *
     * @mbggenerated
     */
    private Integer usagetypeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usagetype.usagetype_chname
     *
     * @mbggenerated
     */
    private String usagetypeChname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usagetype.usagetype_enname
     *
     * @mbggenerated
     */
    private String usagetypeEnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usagetype.usagetype_number
     *
     * @return the value of usagetype.usagetype_number
     *
     * @mbggenerated
     */
    public Integer getUsagetypeNumber() {
        return usagetypeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usagetype.usagetype_number
     *
     * @param usagetypeNumber the value for usagetype.usagetype_number
     *
     * @mbggenerated
     */
    public void setUsagetypeNumber(Integer usagetypeNumber) {
        this.usagetypeNumber = usagetypeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usagetype.usagetype_chname
     *
     * @return the value of usagetype.usagetype_chname
     *
     * @mbggenerated
     */
    public String getUsagetypeChname() {
        return usagetypeChname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usagetype.usagetype_chname
     *
     * @param usagetypeChname the value for usagetype.usagetype_chname
     *
     * @mbggenerated
     */
    public void setUsagetypeChname(String usagetypeChname) {
        this.usagetypeChname = usagetypeChname == null ? null : usagetypeChname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usagetype.usagetype_enname
     *
     * @return the value of usagetype.usagetype_enname
     *
     * @mbggenerated
     */
    public String getUsagetypeEnname() {
        return usagetypeEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usagetype.usagetype_enname
     *
     * @param usagetypeEnname the value for usagetype.usagetype_enname
     *
     * @mbggenerated
     */
    public void setUsagetypeEnname(String usagetypeEnname) {
        this.usagetypeEnname = usagetypeEnname == null ? null : usagetypeEnname.trim();
    }
}